# Generated by Django 4.2.2 on 2023-12-03 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bestfriends',
            new_name='friends',
        ),
        migrations.RenameField(
            model_name='company_details',
            old_name='bestfriend',
            new_name='friend',
        ),
    ]
